project:
  type: website
  output-dir: docs

website:
  title: "PSCI 3200 Final Project"
  navbar:
    left:
      - href: project.qmd
        text: Project
      - about.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



